//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementCinemaBookings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CinemaScreening
    {        
        public CinemaScreening()
        {
            this.CinemaTicketBookings = new HashSet<CinemaTicketBooking>();
        }
    
        public int Id { get; set; }
        public DateTime ScreeningStart { get; set; }
        public DateTime ScreeningEnd { get; set; }
        public short SoldSeats { get; set; }
        public int HallId { get; set; }
        public int MovieId { get; set; }   
        public virtual CinemaHall CinemaHall { get; set; }
        public virtual CinemaMovie CinemaMovie { get; set; }        
        public virtual ICollection<CinemaTicketBooking> CinemaTicketBookings { get; set; }
    }
}