//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementCinemaBookings.Models
{    
    using System.Collections.Generic;
    
    public partial class CinemaHall
    {       
        public CinemaHall()
        {
            this.CinemaScreenings = new HashSet<CinemaScreening>();
        }
    
        public int Id { get; set; }
        public string CinemaCity { get; set; }
        public string CinemaAddress { get; set; }
        public string CinemaName { get; set; }
        public string HallName { get; set; }
        public string HallType { get; set; }
        public short SeatCapacity { get; set; }            
        public virtual ICollection<CinemaScreening> CinemaScreenings { get; set; }
    }
}