//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementCinemaBookings.Models
{    
    using System.Collections.Generic;
    
    public partial class CinemaEmployeeType
    {        
        public CinemaEmployeeType()
        {
            this.CinemaEmployees = new HashSet<CinemaEmployee>();
        }
    
        public int Id { get; set; }
        public string EmployeeTypeName { get; set; }
        public byte EmployeeTypeNo { get; set; }            
        public virtual ICollection<CinemaEmployee> CinemaEmployees { get; set; }
    }
}