//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementCinemaBookings.Models
{    
    using System.Collections.Generic;
    
    public partial class CinemaEmployee
    {        
        public CinemaEmployee()
        {
            this.CinemaTicketBookings = new HashSet<CinemaTicketBooking>();
        }
    
        public int Id { get; set; }
        public string EmployeeName { get; set; }
        public short EmployeeAge { get; set; }
        public string EmployeeGender { get; set; }
        public string EmployeePIDN { get; set; }
        public string EmployeeCountry { get; set; }
        public string EmployeeCity { get; set; }
        public string EmployeePhoneNumber { get; set; }
        public string EmployeeEmailAddress { get; set; }
        public string EmployeePassword { get; set; }
        public int EmployeeTypeId { get; set; }           
        public virtual ICollection<CinemaTicketBooking> CinemaTicketBookings { get; set; }
        public virtual CinemaEmployeeType CinemaEmployeeType { get; set; }
    }
}