//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementCinemaBookings.Models
{    
    using System.Collections.Generic;
    
    public partial class CinemaMovie
    {        
        public CinemaMovie()
        {
            this.CinemaScreenings = new HashSet<CinemaScreening>();
            this.CinemaTicketBookings = new HashSet<CinemaTicketBooking>();
        }
    
        public int Id { get; set; }
        public string MovieName { get; set; }
        public string MovieDirector { get; set; }
        public string MovieGenre { get; set; }
        public string MovieIssuanceCountry { get; set; }
        public short MovieIssuanceYear { get; set; }
        public short MovieRuntime { get; set; }            
        public virtual ICollection<CinemaScreening> CinemaScreenings { get; set; }        
        public virtual ICollection<CinemaTicketBooking> CinemaTicketBookings { get; set; }
    }
}