//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementCinemaBookings.Models
{    
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManagementCinemaBookingsDBEntities : DbContext
    {
        public ManagementCinemaBookingsDBEntities()
            : base("name=ManagementCinemaBookingsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CinemaEmployee> CinemaEmployees { get; set; }
        public virtual DbSet<CinemaEmployeeType> CinemaEmployeeTypes { get; set; }
        public virtual DbSet<CinemaHall> CinemaHalls { get; set; }
        public virtual DbSet<CinemaMovie> CinemaMovies { get; set; }
        public virtual DbSet<CinemaScreening> CinemaScreenings { get; set; }
        public virtual DbSet<CinemaTicketBooking> CinemaTicketBookings { get; set; }

        public System.Data.Entity.DbSet<ManagementCinemaBookings.ViewModels.CinemaEmployeeVM> CinemaEmployeeVMs { get; set; }
    }
}